name: Deploy to FTP

on:
  push:
    branches:
      - main # Upewnij się, że to nazwa Twojej głównej gałęzi (czasem to 'master')

jobs:
  web-deploy:
    name: Build and Deploy to FTP
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🏗️ Build project
        run: npm run build

      - name: 🚀 Sync files to Main Domain
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./dist/ 
          server-dir: public_html/licznikpowtorzen.pl/
          state-name: .deploy-main.json
          exclude: |
            **/*.map
            .git*
            .github*

      - name: 💤 Wait for server
        run: sleep 10

      - name: 🚀 Sync files to Subdomain
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./dist/ 
          server-dir: public_html/pwa.licznikpowtorzen.pl/
          state-name: .deploy-subdomain.json
          exclude: |
            **/*.map
            .git*
            .github*
